twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        google_places_api_key: '%env(GOOGLE_PLACES_API_KEY)%'

when@test:
    twig:
        strict_variables: true
